# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('category', models.CharField(choices=[('SP', 'Sports'), ('BU', 'Buisness'), ('EN', 'Entertainment'), ('TE', 'Technology')], default='EN', max_length=2)),
                ('published', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
